# Note that the prefix in the npm commands forces npm to use the src folder.
include:
  - project: cm-tm/cm-team/pipelineartifacts/pipeline
    ref: "1"
    file : base.yaml
  - project: cm-tm/cm-team/pipelineartifacts/pipeline
    ref: "1"
    file : image.yaml
  - project: cm-tm/cm-team/pipelineartifacts/pipeline
    ref: "1"
    file : chart.yaml
  - project: cm-tm/cm-team/pipelineartifacts/pipeline
    ref: "1"
    file : deploy.yaml
  - project: cm-tm/cm-team/pipelineartifacts/pipeline
    ref: "1"
    file : go.yaml
  - local: 'variables.yaml'

